logging:
  level:
    org.springframework:
      transaction.interceptor: trace
      jdbc.datasource.DataSourceTransactionManager: debug
      orm.jpa.JpaTransactionManager: debug
    org.hibernate:
      resource.transaction: debug
      SQL: debug
